apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: platform
  namespace: argocd

spec:
  project: xae

  source:
    repoURL: https://github.com/XavierianAerospace/platform-charts.git
    targetRevision: main
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

